### ISSUE TITLE
Module (cms) version information not found in the database.

### ISSUE THREAD

**Issue by Legin76** [damanic/ls1-module-cms#2]
I've had an issue one all orders after I tried this plugin.. My receipt page is not working so put the old cms module back. I tried to run an update to make sure everything reverted but when it's doing the checks before I can upgrade it brings up the error "Module (cms) version information not found in the database." The cms version is currently showing as 1.20.1

I'm assuming that something relating to my payment module doesn't like. I can restore the site to yesterdays backup but it would loose the new orders so want to avoid that if I can.

**Comment by damanic** [comment]
This is not a plugin, it is a replacement update to the core CMS module in lemonstand that fixed an issue with GA tracking after google discontinued the API.  

I cannot see how the changes in GA would effect your receipt page. What happened, was an error output or logged?

You do not need to restore the site yesterdays backup, just restore the old 'cms' folder. This does not effect orders in any way.

To restore the lemonstand update feature you should check that v1.20.1 is no longer in the cms/version.dat.

Also remove the 1.2 update entries for 'cms' from your DB table `core_applied_updates`

There are no updates coming from lemonstand anymore so moving on means leaving the 'update' feature behind.

**Comment by damanic** [comment]
oh and you will probably need to change the 'cms' entry in table `core_versions` back to 1.10.37  (afaik thats the last update from lemonstand).

**Comment by Legin76** [comment]
Order tracking code is output on or in the callback page so google can show conversions. I'm assuming that's what the issue is something is messing up with that...

I've changed the core_versions back to 1.10.37 as well as core_applied_updates and removing the update history. but am still getting the Module (cms) version information not found in the database error

I think I need to restore to yesterday then do some tests. Thanks for your help.

**Comment by damanic** [comment]
Ok. I would be interested to hear about it if you find the issue.

Best to try updates on a clone of your live site.

I run sites with this version of CMS and have no issues. But all have the following settings on the 'Google Analytics' Tab on System > Settings > Statistics  ( {youradminurl}/cms/settings/stats/ )

Enable Google Analytics integration : OFF
Enable Google Analytics tracking: ON

And the 'Built in Statistics' are set to ON.

There is no point setting Enable Google Analytics Int. to ON. The API does not work. This CMS version allows you to switch it off whilst still being able to use tracking.

It would be better if the CMS module was updated to use the latest GA API so that its functionality is fully restored.

**Comment by Legin76** [comment]
Ok I've restored and everything is working again.. I can't be 100% sure that it was this that caused it so I'm trying it again.. I've deleted all the content in the modules/cms directory and replaced it with the ones from this.. The Enable Google Analytics tracking option is now there but will not stay turned on... I'm sure yesterday it would.. Previous to this I added the tracking code myself but analytics was showing the referrer as the payment company. The analytics via the system worked correctly before the API issue.

**Comment by damanic** [comment]
When you do an update, logout of admin and log back in. This will run any update scripts to DB. Your GA Tracking switch is not sticking because the field does not exist in the database.

I noticed looking at it now that you cannot edit the GA details without enabling the integration switch first. The tracking switch should be revealing these settings also. Will update.

Tracking uses the CMS page action to add tracking code to all pages.  Integration is indeed called on the receipt page, so disabling integration should solve your issue.   

I hope to update the module to restore full GA integration some time soon.

**Comment by Legin76** [comment]
Exiting the admin did the trick.. The payment page issue appears to be ok now.. Maybe I did something else to mess it up that's related yesterday. I'll wait for a legitimate order to see if the tracking is working all the way though now.

Thank you.. Looking forward to full integration if and when you can do it.

**Comment by damanic** [comment]
pushed an update: full integration restored.

**Comment by Legin76** [comment]
Nice work.. It took me quite a while to get the key working with it.  The instructions at https://developers.google.com/api-client-library/php/auth/web-app are a little broad and caused more confusion than help. I had to add the service account email address as a user in analytics... Thank you so much for sharing this.
